server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:stats_db
spring.datasource.username=test
spring.datasource.password=test
