services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats_db
      - POSTGRES_PASSWORD=12345

  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=main_db
      - POSTGRES_PASSWORD=12345

  users-db:
    image: postgres:16.1
    container_name: users-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=users_db
      - POSTGRES_PASSWORD=12345

  subs-db:
    image: postgres:16.1
    container_name: subs-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=subs_db
      - POSTGRES_USER=subs_db
      - POSTGRES_PASSWORD=12345

  request-db:
    image: postgres:16.1
    container_name: requests-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=request_db
      - POSTGRES_USER=request_db
      - POSTGRES_PASSWORD=12345