grpc:
  server:
    port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6546/analyzer_db
    username: analyzer_db
    password: 12345

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
    user-actions:
      value-deserializer: ru.yandex.practicum.stats.avro.deserializer.UserActionDeserializer
      topic: stats.user-actions.v1
      group-id: analyzer-user-actions-group
      client-id: analyzer-user-actions-client
    event-similarity:
      value-deserializer: ru.yandex.practicum.stats.avro.deserializer.EventSimilarityDeserializer
      topic: stats.events-similarity.v1
      group-id: analyzer-similarity-group
      client-id: analyzer-similarity-client