app.name=ewm-main-service

server.port=8080
stats-server.url=http://localhost:9090

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:main_db
spring.datasource.username=test
spring.datasource.password=test
