CREATE TABLE IF NOT EXISTS users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(120) NOT NULL,
    annotation              VARCHAR(2000) NOT NULL,
    category_id             BIGINT,
    paid                    BOOLEAN NOT NULL,
    event_date              TIMESTAMP NOT NULL,
    initiator_id            BIGINT NOT NULL,
    lat                     DOUBLE PRECISION NOT NULL,
    lon                     DOUBLE PRECISION NOT NULL,
    description             VARCHAR(7000) NOT NULL,
    participant_limit       INTEGER NOT NULL,
    state                   VARCHAR(20) NOT NULL,
    created_on              TIMESTAMP NOT NULL,
    published_on            TIMESTAMP,
    requested_moderation    BOOLEAN NOT NULL,

    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created                 TIMESTAMP NOT NULL,
    event_id                BIGINT NOT NULL,
    requester_id            BIGINT NOT NULL,
    status                  VARCHAR(20) NOT NULL,

    CONSTRAINT fk_request_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_request_requester_id FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  VARCHAR(255) NOT NULL,
    pinned                 BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_to_events
(
    event_id               BIGINT NOT NULL,
    compilation_id         BIGINT NOT NULL,

    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions
(
    id                     BIGSERIAL PRIMARY KEY,
    follower_id            BIGINT NOT NULL,
    followed_id            BIGINT NOT NULL,
    created                TIMESTAMP NOT NULL,

    CONSTRAINT fk_subscription_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_followed FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_follower_followed UNIQUE (follower_id, followed_id)
);