server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**

        - id: main-service-public-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**

        - id: main-service-public-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**

        - id: main-service-public-events
          uri: lb://main-service
          predicates:
            - Path=/events/**

        - id: main-service-private-users
          uri: lb://main-service
          predicates:
            - Path=/users/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats