server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: subscription-service-route
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**, /users/*/subscriptions/**, /users/*/subscriptions/*

        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests/**, /users/events/requests/confirmed, /users/events/*/requests/confirmed

        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**, /admin/events/**, /admin/compilations/**, /compilations/**, /events/**, /internal/events/**, /admin/categories/**, /categories/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**,/admin/users/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats