server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/main_db
    username: main_db
    password: 12345

app:
  name: ewm-main-service

resilience4j:
  circuitbreaker:
    instances:
      DemoClientgetDemo:
        minimumNumberOfCalls: 69
  timelimiter:
    instances:
      DemoClientgetDemo:
        timeoutDuration: 10s
  retry:
    instances:
      retryGet:
        max-attempts: 3
        wait-duration: 1s